#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = "log"
color = "auto"
pager = "delta"
diff-formatter = ":git"

# To use difftastic instead, comment out diff-formatter above and uncomment:
# [ui.diff]
# tool = ["difft", "--color=always"]

[user]
name = "Adam McCullough"
email = "merlinfmct87@gmail.com"

[git]
push-bookmark-prefix = "amccullough/"

[remotes.origin]
auto-track-bookmarks = "*"

[[--scope]]
--when.repositories = [
  "~/work",
  "~/cravin-rs-fresh",
  "~/cravin-rs-second-thread",
  "~/cravin-rs-third-thread",
]
[--scope.user]
email = "adam@cravin.com"

[merge-tools.mergiraf]
program = "mergiraf"

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[merge-tools.imediff]
program = "imediff"
merge-args = ["$left", "$base", "$right", "-o", "$output"]
merge-tool-edits-conflict-markers = true
