#!/usr/bin/env bash
# vim: ft=bash
set -euo pipefail

function link_file() {
  SRC="${1}"
  shift
  DEST="${1}"
  shift

  mkdir -p $(dirname "${DEST}")

  if [ -L "${DEST}" ]; then
    echo "File ${DEST} already linked; skipping"
  elif [ -e "${DEST}" ]; then
    mv "${DEST}" "${DEST}_$(date +%s)"
    ln -s "${SRC}" "${DEST}"
  else
    # Neither already linked, nor a concrete file.
    ln -s "${SRC}" "${DEST}"
  fi
}

link_file "${HOME}/abrazo/alias" "${HOME}/.alias"
link_file "${HOME}/abrazo/alias.sh" "${HOME}/.alias.sh"
link_file "${HOME}/abrazo/api_keys.sh" "${HOME}/.api_keys.sh"
link_file "${HOME}/abrazo/tmux.conf" "${HOME}/.tmux.conf"
link_file "${HOME}/abrazo/tmux/config.sh" "${HOME}/.config/tmux-powerline/config.sh"
link_file "${HOME}/abrazo/tmux/merlin.sh" "${HOME}/.config/tmux-powerline/themes/merlin.sh"
link_file "${HOME}/abrazo/bashrc" "${HOME}/.bashrc"
link_file "${HOME}/abrazo/bash_profile" "${HOME}/.bash_profile"

link_file "${HOME}/abrazo/emacs.d" "${HOME}/.emacs.d"

link_file "${HOME}/abrazo/nvim" "${HOME}/.config/nvim"
link_file "${HOME}/abrazo/nvim" "${HOME}/.var/app/io.neovim.nvim/config/nvim"

pushd fish
./fish_install.fish
popd

OS=$(uname | tr 'A-Z' 'a-z')

link_file "${HOME}/kitty/font-${OS}.conf" "${HOME}/.config/kitty/font.conf"

export fileList=("current-theme" "kitty" "ligatures")

for file in ${fileList[@]}; do
  link_file "${HOME}/abrazo/kitty/${file}.conf" "${HOME}/.config/kitty/${file}.conf"
done

if [ -d "${HOME}/.tmux/plugins/tpm" ]; then
  pushd "${HOME}/.tmux/plugins/tpm"
  git pull
  popd
else
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
