#!/usr/bin/env bash
set -euo pipefail

mkdir -p ~/.config/tmux-powerline
if [ ! -e ~/.config/tmux-powerline/config.sh ]; then
	ln -s ./tmux/config.sh ~/.config/tmux-powerline/config.sh
fi
mkdir -p ~/.tmux/plugins/tmux-powerline/themes
if [ ! -e ~/.tmux/plugins/tmux-powerline/themes/merlin.sh ]; then
	ln -s ./tmux/merlin.sh ~/.tmux/plugins/tmux-powerline/themes/merlin.sh
fi

pushd fish
./fish_install.fish
popd
