# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/merlin/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
resolver: lts-15.1

allow-newer: true

extra-deps:
  # for pandoc
  - cheapskate-0.1.1.2@sha256:74df5ffc40ce20f7df7ff99296dd94ae4ebf59366880592f31418e286fb70d22,3058
